language: ruby
sudo: false
cache: bundler
script: 'bundle exec rake test:coverage --trace'
before_install:
  - gem install bundler
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-18mode
  - jruby
  - jruby-head
  - rbx-2
